version: '3'
services:
  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    depends_on:
      - sonarqube
    networks:
      - sonarnet
    volumes:
      - ${PROJECT_PATH:-.}:/usr/src
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000

networks:
  sonarnet:

volumes:
  sonarqube_data:
