apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2  # Количество воркеров
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: cr.yandex/crp2a0s6kjm2a7nidir9/worker
        env:
        - name: WORKER_ID  # Опционально: можно передавать переменные
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"