apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-bandit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-bandit
  template:
    metadata:
      labels:
        app: worker-bandit
    spec:
      containers:
      - name: worker-bandit
        image: cr.yandex/crptukhsim5k1t3buhev/worker
        env:
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-semgrep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-semgrep
  template:
    metadata:
      labels:
        app: worker-semgrep
    spec:
      containers:
      - name: worker-semgrep
        image: cr.yandex/crptukhsim5k1t3buhev/worker
        env:
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
